-- ============================================================================
-- BATCH ORGANIZER — run once in the Supabase SQL editor
-- (Project -> SQL Editor -> New query -> paste -> Run).
--
-- Builds on phone_privacy.sql / member_passcode.sql (must already be applied).
--
-- Replaces the old hardcoded 4-value batch list (Beginner/Intermediate/
-- Advanced/Professional) with a real, admin-editable table of the 5 actual
-- Saturday/Sunday batches, and adds a self-service "request to move batch"
-- flow for members, mirroring request_manual_checkin_by_phone /
-- request_passcode_reset_by_phone exactly.
-- ============================================================================

-- ===== 1. Batches =====
-- students.batch keeps storing the batch NAME (unchanged column/pattern) —
-- editing a batch's day/time here never touches a student row.
create table if not exists public.batches (
    id bigint generated by default as identity primary key,
    name text not null unique,
    day text not null,                    -- 'Saturday' | 'Sunday'
    start_time text not null,             -- e.g. '1:30 PM'
    end_time text not null,               -- e.g. '3:30 PM'
    category text not null,               -- 'beginner' | 'intermediate' | 'advance'
    min_capacity int not null default 8,
    max_capacity int not null default 12,
    sort_order int not null default 0,
    active boolean not null default true
);

-- Same trust model as students/attendance (checkin_settings.sql): RLS off,
-- both the admin dashboard (authenticated) and member.html (anon) read this
-- table directly, and only admin.html exposes any write UI for it.
alter table public.batches disable row level security;

insert into public.batches (name, day, start_time, end_time, category, sort_order)
values
    ('Avanzato 1', 'Saturday', '1:30 PM', '3:30 PM', 'advance', 1),
    ('Avanzato 2', 'Saturday', '3:30 PM', '5:30 PM', 'advance', 2),
    ('Principianti (primo livello)', 'Saturday', '5:30 PM', '7:30 PM', 'beginner', 3),
    ('Principianti (secondo livello)', 'Sunday', '2:00 PM', '4:00 PM', 'beginner', 4),
    ('Intermedio', 'Sunday', '4:00 PM', '6:00 PM', 'intermediate', 5)
on conflict (name) do nothing;

-- ===== 2. Batch change requests =====
-- Mirrors checkin_requests (checkin_settings.sql) exactly, same trust model:
-- RLS off, member.html never writes this table directly (it only ever calls
-- request_batch_change_by_phone below), admin.html reads/writes it directly.
create table if not exists public.batch_change_requests (
    id bigint generated by default as identity primary key,
    student_id bigint not null,
    student_name text not null,
    current_batch text,
    requested_batch text not null,
    status text not null default 'pending', -- 'pending' | 'approved' | 'dismissed'
    requested_at timestamptz not null default now(),
    resolved_at timestamptz
);

alter table public.batch_change_requests disable row level security;

-- ===== 3. RPC: request a batch move (phone + optional passcode verified) ====
-- Returns: 'sent' | 'bad_phone' | 'bad_passcode' | 'unknown_batch'
create or replace function public.request_batch_change_by_phone(
    p_student_id bigint,
    p_phone text,
    p_requested_batch text,
    p_passcode text default null
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_name text;
    v_current_batch text;
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return 'bad_phone';
    end if;

    if not public._passcode_matches_student(p_student_id, p_passcode) then
        return 'bad_passcode';
    end if;

    if not exists (select 1 from public.batches where name = p_requested_batch and active) then
        return 'unknown_batch';
    end if;

    select name, batch into v_name, v_current_batch from public.students where id = p_student_id;

    -- Replace any existing pending request instead of stacking duplicates.
    update public.batch_change_requests
    set status = 'dismissed', resolved_at = now()
    where student_id = p_student_id and status = 'pending';

    insert into public.batch_change_requests (student_id, student_name, current_batch, requested_batch)
    values (p_student_id, v_name, v_current_batch, p_requested_batch);

    return 'sent';
end;
$$;

grant execute on function public.request_batch_change_by_phone(bigint, text, text, text) to anon;
