-- Run this once in the Supabase SQL editor (Project -> SQL Editor -> New query).
-- Creates the single-row settings table that controls when the public
-- self check-in page (checkin.html) is open, and seeds it with the
-- requested default window: Saturday & Sunday, 1:15 PM - 7:00 PM.

create table if not exists public.checkin_settings (
    id smallint primary key default 1,
    active_days smallint[] not null default '{6,0}',  -- JS Date.getDay(): 0=Sun, 6=Sat
    start_time time not null default '13:15:00',
    end_time time not null default '19:00:00',
    updated_at timestamptz not null default now(),
    constraint checkin_settings_singleton check (id = 1)
);

insert into public.checkin_settings (id, active_days, start_time, end_time)
values (1, '{6,0}', '13:15:00', '19:00:00')
on conflict (id) do nothing;

-- Supabase enables RLS with zero policies on every new table by default,
-- which blocks the anon key used by both the admin dashboard and the public
-- check-in page from reading/writing this row at all. The rest of this app's
-- tables run with RLS off, so this matches that same trust model.
alter table public.checkin_settings disable row level security;

-- ===== Manual check-in requests =====
-- When a student can't self check-in (window closed, PIN doesn't match,
-- no phone on file, etc.) they can send a "please mark me manually" request
-- instead. The admin dashboard's Attendance tab shows these as a small
-- pending list and marks the student present with one tap.

create table if not exists public.checkin_requests (
    id bigint generated by default as identity primary key,
    student_id bigint not null,
    student_name text not null,
    reason text,
    status text not null default 'pending', -- 'pending' | 'approved' | 'dismissed' ('resolved' in rows from before the split)
    requested_at timestamptz not null default now(),
    resolved_at timestamptz
);

alter table public.checkin_requests disable row level security;

-- ===== If the check-in page's student search shows nobody, run this =====
-- The admin dashboard only works because it logs in (via Supabase Auth), which
-- can satisfy an RLS policy scoped to the "authenticated" role. checkin.html
-- deliberately never logs in (it's public), so it only ever queries as the
-- anon role — if students/attendance have RLS enabled without an anon-facing
-- policy, checkin.html will silently see zero rows (no error, just empty),
-- which looks exactly like "the search bar isn't working." This makes those
-- two tables match the rest of the app's (already anon-open) trust model.
alter table public.students disable row level security;
alter table public.attendance disable row level security;

-- ===== If the new self-service report page shows nobody's payment data =====
-- Every existing read of fees_paid happens only from the logged-in admin
-- session (authenticated role) — the anon role's access to it has never
-- actually been exercised until report.html. Matches the same trust model
-- as the tables above.
alter table public.fees_paid disable row level security;
