-- ============================================================================
-- PER-CLASS CREDIT PRICING SYSTEM — run once in the Supabase SQL editor
-- (Project -> SQL Editor -> New query -> paste -> Run).
--
-- Adds the new €10/class credit system alongside the existing monthly-cycle
-- engine (membership.js) WITHOUT touching it. A student only moves onto the
-- credit system when their current billing cycle genuinely finishes (see
-- checkAndMigrateToCredit() in admin.html) — nothing changes for anyone
-- until that happens automatically.
-- ============================================================================

alter table public.students add column if not exists credit_balance numeric not null default 0;

-- false = business exactly as today (old cycle engine, incl. its own
-- auto-extension for irregular attendance). true = new credit system applies.
-- Flipped only by checkAndMigrateToCredit() in admin.html, never by hand.
alter table public.students add column if not exists on_credit_plan boolean not null default false;

-- Append-only ledger, same shape/spirit as fees_paid: every recharge and every
-- per-class deduction gets its own row, so a student's balance is always
-- reconstructable/auditable, not just a single mutable number.
create table if not exists public.credit_transactions (
    id bigint generated by default as identity primary key,
    student_id bigint not null,
    type text not null,             -- 'recharge' | 'class_deduction' | 'adjustment'
    amount numeric not null,        -- positive for recharge, negative for deduction
    balance_after numeric not null,
    note text,
    created_at timestamptz not null default now(),
    created_by text
);

-- Same trust model as students/attendance/fees_paid (checkin_settings.sql):
-- RLS off, admin.html reads/writes this directly as the authenticated role.
alter table public.credit_transactions disable row level security;
