-- ============================================================================
-- FATTURE XML — run once in the Supabase SQL editor
-- (Project -> SQL Editor -> New query -> paste -> Run).
--
-- Lets admin.html build the FatturaPA XML (FPR12, privato: codice
-- destinatario 0000000) for a recharge, ready to upload by hand in
-- "Fatture e Corrispettivi" on the Agenzia delle Entrate site. Nothing is
-- sent anywhere automatically.
--
--  1. students.parent_codice_fiscale — when filled, the fattura is made out
--     to the parent (minors); otherwise to the student.
--  2. fattura_settings — one row (id = 1): the studio's own cedente data,
--     IVA treatment, bollo, default description, and where numbering starts.
--  3. fatture — one row per generated fattura. Unique (anno, numero) so a
--     number can never be used twice; unique transaction_id so a recharge
--     can only be invoiced once (a deleted fattura frees both up again).
--
-- Admin-only: same RLS as v2_credit_transactions. Nothing exposed to anon.
-- ============================================================================

alter table public.students add column if not exists parent_codice_fiscale text;

create table if not exists public.fattura_settings (
    id int primary key default 1 check (id = 1),
    -- Cedente / prestatore (the studio)
    denominazione text,          -- business name; leave empty to use nome + cognome
    nome text,
    cognome text,
    partita_iva text,
    codice_fiscale text,
    regime_fiscale text not null default 'RF19',
    indirizzo text,
    numero_civico text,
    cap text,
    comune text,
    provincia text,              -- 2-letter sigla, e.g. CR
    -- IVA
    aliquota_iva numeric not null default 0,
    natura text default 'N2.2',  -- required when aliquota is 0
    riferimento_normativo text,
    -- Bollo
    bollo_enabled boolean not null default true,  -- €2 virtual bollo above €77.47 when no IVA
    -- Content
    descrizione_default text default 'Corso di danza',
    modalita_pagamento text not null default 'MP01', -- MP01 contanti, MP05 bonifico, MP08 carta
    -- Numbering: in start_year, numbers continue from start_number
    start_year int,
    start_number int not null default 1,
    updated_at timestamptz not null default now()
);

insert into public.fattura_settings (id) values (1) on conflict (id) do nothing;

create table if not exists public.fatture (
    id bigint generated by default as identity primary key,
    anno int not null,
    numero int not null,
    data_fattura date not null,
    student_id bigint not null,
    transaction_id bigint,
    recipient_type text not null,      -- 'student' | 'parent'
    recipient_nome text,
    recipient_cognome text,
    recipient_cf text not null,
    importo numeric not null,          -- total paid by the customer
    bollo numeric not null default 0,
    descrizione text,
    file_name text not null,
    xml text not null,
    created_at timestamptz not null default now(),
    deleted_at timestamptz
);

create unique index if not exists fatture_anno_numero_active
    on public.fatture (anno, numero) where deleted_at is null;
create unique index if not exists fatture_transaction_active
    on public.fatture (transaction_id) where deleted_at is null and transaction_id is not null;

alter table public.fattura_settings enable row level security;
alter table public.fatture enable row level security;

drop policy if exists "authenticated_all" on public.fattura_settings;
create policy "authenticated_all" on public.fattura_settings
    for all to authenticated using (true) with check (true);

drop policy if exists "authenticated_all" on public.fatture;
create policy "authenticated_all" on public.fatture
    for all to authenticated using (true) with check (true);

revoke all on public.fattura_settings from anon;
revoke all on public.fatture from anon;
