-- ============================================================================
-- MEDICAL CERTIFICATE UPLOAD (member portal) — run once in the Supabase SQL
-- editor (Project -> SQL Editor -> New query -> paste -> Run).
--
-- Builds on member_passcode.sql (must already be applied).
--
-- Students upload their certificato medico non-agonistico from member.html.
-- It lands in a private, write-only "drop box" bucket + a pending-review
-- queue; the studio admin reviews it in the existing Income & Expense / Tax
-- tab and, if it checks out, promotes it into the tax_records/tax-pdfs data
-- that tab already manages (has_doctor / doctor_pdf_path) — one doctor-
-- certificate record, not two parallel ones.
-- ============================================================================

-- ===== 1. Storage: private, anon can only INSERT (never read/list/update/
-- delete), so a student can never browse another student's uploaded file. =====
insert into storage.buckets (id, name, public)
values ('medical-cert-uploads', 'medical-cert-uploads', false)
on conflict (id) do update set public = false;

drop policy if exists "medical_cert_anon_insert" on storage.objects;
create policy "medical_cert_anon_insert" on storage.objects
    for insert to anon
    with check (bucket_id = 'medical-cert-uploads');

drop policy if exists "medical_cert_authenticated_all" on storage.objects;
create policy "medical_cert_authenticated_all" on storage.objects
    for all to authenticated
    using (bucket_id = 'medical-cert-uploads') with check (bucket_id = 'medical-cert-uploads');

-- ===== 2. Pending-review queue =====
create table if not exists public.medical_certificate_submissions (
    id bigint generated by default as identity primary key,
    student_id bigint not null,
    student_name text not null,
    file_path text not null,
    status text not null default 'pending', -- 'pending' | 'approved' | 'rejected'
    submitted_at timestamptz not null default now(),
    reviewed_at timestamptz
);

-- Same trust model as students/attendance (checkin_settings.sql): RLS off,
-- admin.html reads/writes this directly as the authenticated role. The
-- sensitive part (the actual file) is protected at the bucket level above,
-- not here — this table only ever holds a path + status, no medical data.
alter table public.medical_certificate_submissions disable row level security;

-- ===== 3. RPC: submit a certificate (phone + optional passcode verified) ====
-- The file itself is uploaded straight to storage by member.html (allowed by
-- the anon-insert policy above); this RPC just registers that upload against
-- the student it actually belongs to. Returns: 'sent' | 'bad_phone' | 'bad_passcode'
create or replace function public.submit_medical_certificate_by_phone(
    p_student_id bigint,
    p_phone text,
    p_file_path text,
    p_passcode text default null
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_name text;
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return 'bad_phone';
    end if;

    if not public._passcode_matches_student(p_student_id, p_passcode) then
        return 'bad_passcode';
    end if;

    select name into v_name from public.students where id = p_student_id;

    -- A fresh upload supersedes any earlier pending one instead of stacking.
    delete from public.medical_certificate_submissions
    where student_id = p_student_id and status = 'pending';

    insert into public.medical_certificate_submissions (student_id, student_name, file_path)
    values (p_student_id, v_name, p_file_path);

    return 'sent';
end;
$$;

grant execute on function public.submit_medical_certificate_by_phone(bigint, text, text, text) to anon;

-- ===== 4. RPC: check certificate status (phone-verified read) ===============
-- tax_records is locked down to the authenticated role only (security_lockdown.sql
-- revokes anon entirely — it's where "sensitive" tax/doctor-cert data lives),
-- so member.html can't read it directly. This is a narrow, read-only window
-- into just the one flag a student needs to see about themselves.
-- Returns: 'approved' | 'pending' | 'none' | 'bad_phone' | 'bad_passcode'
create or replace function public.get_medical_certificate_status_by_phone(
    p_student_id bigint,
    p_phone text,
    p_passcode text default null
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_has_doctor boolean;
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return 'bad_phone';
    end if;

    if not public._passcode_matches_student(p_student_id, p_passcode) then
        return 'bad_passcode';
    end if;

    select has_doctor into v_has_doctor from public.tax_records where student_id = p_student_id;
    if v_has_doctor then
        return 'approved';
    end if;

    if exists (
        select 1 from public.medical_certificate_submissions
        where student_id = p_student_id and status = 'pending'
    ) then
        return 'pending';
    end if;

    return 'none';
end;
$$;

grant execute on function public.get_medical_certificate_status_by_phone(bigint, text, text) to anon;
