-- ============================================================================
-- OPTIONAL MEMBER PASSCODE — run once in the Supabase SQL editor
-- (Project -> SQL Editor -> New query -> paste -> Run).
--
-- Builds on phone_privacy.sql (must already be applied — it is).
--
-- The phone number stays the identity (find_members_by_phone is unchanged in
-- shape, it just now also reports whether a passcode is set). A member may
-- optionally set a 4-digit passcode on their own record. Once set, every
-- action RPC requires phone + passcode together instead of phone alone.
--
-- Forgetting it is NOT self-service: the member requests a reset
-- (request_passcode_reset_by_phone), which the studio admin approves in
-- admin.html. Approving clears passcode_hash, which immediately restores
-- phone-only access AND re-offers the "set a passcode" opt-in next time —
-- both recovery paths the studio asked for, from a single admin action.
-- ============================================================================

-- Supabase installs pgcrypto into the "extensions" schema by default; if it's
-- not there yet this creates it there, if it already is this is a no-op.
create extension if not exists pgcrypto with schema extensions;

-- ===== 1. Schema =============================================================
alter table public.students add column if not exists passcode_hash text;

-- Mirrors checkin_requests (checkin_settings.sql) exactly, same trust model.
create table if not exists public.passcode_reset_requests (
    id bigint generated by default as identity primary key,
    student_id bigint not null,
    student_name text not null,
    status text not null default 'pending', -- 'pending' | 'approved' | 'dismissed'
    requested_at timestamptz not null default now(),
    resolved_at timestamptz
);

-- Unlike checkin_requests, this table has RLS ON with no anon policy at all:
-- the only write anon can ever make is through request_passcode_reset_by_phone
-- below, which is security definer (runs as the table owner, so RLS never
-- applies to it) -- direct REST access with the anon key is blocked outright.
-- admin.html reads/writes this table directly as the authenticated role, so
-- it needs its own policy, same "authenticated_all" pattern as performances.sql
-- and site_content.sql.
alter table public.passcode_reset_requests enable row level security;

drop policy if exists "authenticated_all" on public.passcode_reset_requests;
create policy "authenticated_all" on public.passcode_reset_requests
    for all to authenticated using (true) with check (true);

-- ===== 2. Passcode-matching helper (not callable from outside) ==============
-- Returns true automatically when the student has no passcode set, so every
-- gated RPC below is a no-op change for members who never opted in.
create or replace function public._passcode_matches_student(p_student_id bigint, p_passcode text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
    v_hash text;
begin
    select passcode_hash into v_hash from public.students where id = p_student_id;

    if v_hash is null then
        return true;
    end if;

    return v_hash = crypt(coalesce(p_passcode, ''), v_hash);
end;
$$;

revoke execute on function public._passcode_matches_student(bigint, text) from public, anon;

-- ===== 3. RPC: who is registered under this phone number? ===================
-- Same shape as phone_privacy.sql's version, plus has_passcode per member so
-- the page knows whether to show the passcode-entry step or the opt-in prompt.
create or replace function public.find_members_by_phone(p_phone text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_entered text := public._phone_digits(p_phone);
    v_members jsonb;
begin
    if length(v_entered) < 9 then
        return jsonb_build_object('status', 'invalid');
    end if;

    select jsonb_agg(jsonb_build_object(
        'id', s.id,
        'name', s.name,
        'has_passcode', s.passcode_hash is not null
    ) order by s.name)
    into v_members
    from public.students s
    where length(public._phone_digits(s.phone)) >= 9
      and right(public._phone_digits(s.phone), 9) = right(v_entered, 9);

    if v_members is null then
        return jsonb_build_object('status', 'not_found');
    end if;

    return jsonb_build_object('status', 'ok', 'members', v_members);
end;
$$;

grant execute on function public.find_members_by_phone(text) to anon;

-- ===== 4. RPC: set a passcode (first time, or right after an admin reset) ===
-- Only succeeds while passcode_hash is null — changing a remembered passcode
-- isn't a supported path by design; forgetting it always goes through admin
-- approval (request_passcode_reset_by_phone below), which nulls it out.
-- Returns: 'ok' | 'bad_phone' | 'invalid_format' | 'already_set'
create or replace function public.set_student_passcode_by_phone(
    p_student_id bigint,
    p_phone text,
    p_passcode text
)
returns text
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return 'bad_phone';
    end if;

    if p_passcode !~ '^\d{4}$' then
        return 'invalid_format';
    end if;

    if exists (select 1 from public.students where id = p_student_id and passcode_hash is not null) then
        return 'already_set';
    end if;

    update public.students
    set passcode_hash = crypt(p_passcode, gen_salt('bf'))
    where id = p_student_id;

    return 'ok';
end;
$$;

grant execute on function public.set_student_passcode_by_phone(bigint, text, text) to anon;

-- ===== 5. RPC: "I forgot my passcode" (phone-verified) ======================
-- Queues an admin-approval request. Duplicate pending requests from the same
-- student are collapsed, same pattern as request_manual_checkin_by_phone.
-- Returns: 'sent' | 'bad_phone' | 'no_passcode'
create or replace function public.request_passcode_reset_by_phone(p_student_id bigint, p_phone text)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_name text;
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return 'bad_phone';
    end if;

    select name into v_name from public.students where id = p_student_id and passcode_hash is not null;

    if v_name is null then
        return 'no_passcode';
    end if;

    if exists (
        select 1 from public.passcode_reset_requests
        where student_id = p_student_id and status = 'pending'
    ) then
        return 'sent'; -- already queued, don't spam the admin
    end if;

    insert into public.passcode_reset_requests (student_id, student_name)
    values (p_student_id, v_name);

    return 'sent';
end;
$$;

grant execute on function public.request_passcode_reset_by_phone(bigint, text) to anon;

-- ===== 6. Gate the existing action RPCs with an optional passcode ===========
-- Each gains a p_passcode parameter (default null, so a student with no
-- passcode set is completely unaffected). Old 2-arg / 2-arg+reason signatures
-- are dropped first — Postgres treats a changed parameter list as a distinct
-- function, and leaving both around makes PostgREST's named-argument RPC
-- calls ambiguous.

drop function if exists public.checkin_self_by_phone(bigint, text);

-- Returns: 'checked_in' | 'already' | 'bad_phone' | 'bad_passcode' | 'closed'
create or replace function public.checkin_self_by_phone(
    p_student_id bigint,
    p_phone text,
    p_passcode text default null
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_settings public.checkin_settings%rowtype;
    v_now_rome timestamp := (now() at time zone 'Europe/Rome');
    v_today    date      := (now() at time zone 'Europe/Rome')::date;
    v_existing public.attendance%rowtype;
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return 'bad_phone';
    end if;

    if not public._passcode_matches_student(p_student_id, p_passcode) then
        return 'bad_passcode';
    end if;

    select * into v_settings from public.checkin_settings where id = 1;
    if not found
       or not (extract(dow from v_now_rome)::smallint = any (v_settings.active_days))
       or v_now_rome::time < v_settings.start_time
       or v_now_rome::time > v_settings.end_time then
        return 'closed';
    end if;

    select * into v_existing
    from public.attendance
    where studentid = p_student_id and attendancedate = v_today
    limit 1;

    if found then
        if v_existing.ispresent then
            return 'already';
        end if;
        update public.attendance
        set ispresent = true
        where id = v_existing.id;
        return 'checked_in';
    end if;

    insert into public.attendance (studentid, attendancedate, ispresent, isdemo)
    values (p_student_id, v_today, true, false);
    return 'checked_in';
end;
$$;

grant execute on function public.checkin_self_by_phone(bigint, text, text) to anon;

drop function if exists public.request_manual_checkin_by_phone(bigint, text, text);

-- Returns: 'sent' | 'already' | 'bad_phone' | 'bad_passcode'
create or replace function public.request_manual_checkin_by_phone(
    p_student_id bigint,
    p_phone text,
    p_reason text default null,
    p_passcode text default null
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_today  date := (now() at time zone 'Europe/Rome')::date;
    v_name   text;
    v_reason text;
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return 'bad_phone';
    end if;

    if not public._passcode_matches_student(p_student_id, p_passcode) then
        return 'bad_passcode';
    end if;

    v_reason := left(coalesce(nullif(trim(p_reason), ''), 'Check-in issue'), 120);

    select name into v_name from public.students where id = p_student_id;

    if exists (
        select 1 from public.attendance
        where studentid = p_student_id and attendancedate = v_today and ispresent
    ) then
        return 'already';
    end if;

    if exists (
        select 1 from public.checkin_requests
        where student_id = p_student_id
          and status = 'pending'
          and requested_at >= v_today
    ) then
        return 'sent'; -- already queued today, don't spam the instructor
    end if;

    insert into public.checkin_requests (student_id, student_name, reason)
    values (p_student_id, v_name, v_reason);
    return 'sent';
end;
$$;

grant execute on function public.request_manual_checkin_by_phone(bigint, text, text, text) to anon;

drop function if exists public.get_student_report_by_phone(bigint, text);

create or replace function public.get_student_report_by_phone(
    p_student_id bigint,
    p_phone text,
    p_passcode text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return jsonb_build_object('status', 'bad_phone');
    end if;

    if not public._passcode_matches_student(p_student_id, p_passcode) then
        return jsonb_build_object('status', 'bad_passcode');
    end if;

    return jsonb_build_object(
        'status', 'ok',
        'student', (
            select jsonb_build_object(
                'id', s.id,
                'name', s.name,
                'parentname', s.parentname,
                'joindate', s.joindate,
                'nextpaymentdate', s.nextpaymentdate,
                'monthlyfees', s.monthlyfees
            )
            from public.students s
            where s.id = p_student_id
        ),
        'attendance', coalesce((
            select jsonb_agg(jsonb_build_object(
                'studentid', a.studentid,
                'attendancedate', a.attendancedate,
                'ispresent', a.ispresent,
                'isdemo', a.isdemo
            ) order by a.attendancedate)
            from public.attendance a
            where a.studentid = p_student_id
        ), '[]'::jsonb),
        'fees', coalesce((
            select jsonb_agg(to_jsonb(f) order by f.id)
            from public.fees_paid f
            where f.studentid = p_student_id
        ), '[]'::jsonb)
    );
end;
$$;

grant execute on function public.get_student_report_by_phone(bigint, text, text) to anon;

-- ===== 7. RPC: change an existing passcode (member already knows the old one) =====
-- Unlike set_student_passcode_by_phone (first-time / post-reset only), this
-- lets a member who can supply their CURRENT passcode pick a new one
-- themselves, right from their dashboard -- standard "change password"
-- semantics, no admin involved. Forgetting the old one still only goes
-- through admin approval (request_passcode_reset_by_phone above).
-- Returns: 'ok' | 'bad_phone' | 'no_passcode_set' | 'bad_old_passcode' | 'invalid_format'
create or replace function public.change_student_passcode_by_phone(
    p_student_id bigint,
    p_phone text,
    p_old_passcode text,
    p_new_passcode text
)
returns text
language plpgsql
security definer
set search_path = public, extensions, pg_temp
as $$
declare
    v_hash text;
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return 'bad_phone';
    end if;

    select passcode_hash into v_hash from public.students where id = p_student_id;
    if v_hash is null then
        return 'no_passcode_set';
    end if;

    if v_hash != crypt(coalesce(p_old_passcode, ''), v_hash) then
        return 'bad_old_passcode';
    end if;

    if p_new_passcode !~ '^\d{4}$' then
        return 'invalid_format';
    end if;

    update public.students
    set passcode_hash = crypt(p_new_passcode, gen_salt('bf'))
    where id = p_student_id;

    return 'ok';
end;
$$;

grant execute on function public.change_student_passcode_by_phone(bigint, text, text, text) to anon;

-- ===== 8. Gate the performances.sql RPCs the same way (member.html "Perform" tab) =====
-- Same p_passcode default-null treatment as section 6 above, so the
-- Members/Attendance/Perform tabs are all consistently gated.

drop function if exists public.join_performance_by_phone(bigint, bigint, text);

-- Returns: 'joined' | 'closed' | 'not_found' | 'bad_phone' | 'bad_passcode'
create or replace function public.join_performance_by_phone(
    p_performance_id bigint,
    p_student_id bigint,
    p_phone text,
    p_passcode text default null
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_status text;
    v_name   text;
    v_batch  text;
    v_tier   text;
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return 'bad_phone';
    end if;

    if not public._passcode_matches_student(p_student_id, p_passcode) then
        return 'bad_passcode';
    end if;

    select status into v_status from public.performances where id = p_performance_id;
    if v_status is null then
        return 'not_found';
    end if;
    if v_status <> 'open' then
        return 'closed';
    end if;

    select name, batch into v_name, v_batch from public.students where id = p_student_id;

    v_tier := case
        when v_batch in ('Advanced', 'Professional') then 'advanced'
        when v_batch = 'Intermediate' then 'intermediate'
        else 'beginner'
    end;

    insert into public.performance_signups (performance_id, student_id, student_name, roster_status)
    values (p_performance_id, p_student_id, v_name, v_tier)
    on conflict (performance_id, student_id) do nothing;

    return 'joined';
end;
$$;

grant execute on function public.join_performance_by_phone(bigint, bigint, text, text) to anon;

drop function if exists public.get_my_spot_by_phone(bigint, text);

-- Returns status: 'bad_phone' | 'bad_passcode' | 'not_joined' | 'no_movements' | 'ok'
create or replace function public.get_my_spot_by_phone(
    p_student_id bigint,
    p_phone text,
    p_passcode text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_signup   public.performance_signups%rowtype;
    v_movement public.performance_movements%rowtype;
    v_pos      public.performance_positions%rowtype;
    v_row_band text;
    v_col_band text;
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return jsonb_build_object('status', 'bad_phone');
    end if;

    if not public._passcode_matches_student(p_student_id, p_passcode) then
        return jsonb_build_object('status', 'bad_passcode');
    end if;

    select * into v_signup
    from public.performance_signups
    where student_id = p_student_id
    order by joined_at desc
    limit 1;

    if not found then
        return jsonb_build_object('status', 'not_joined');
    end if;

    select * into v_movement
    from public.performance_movements
    where performance_id = v_signup.performance_id
    order by movement_order desc
    limit 1;

    if not found then
        return jsonb_build_object('status', 'no_movements');
    end if;

    select * into v_pos
    from public.performance_positions
    where movement_id = v_movement.id and student_id = p_student_id;

    if not found then
        return jsonb_build_object('status', 'no_movements');
    end if;

    v_row_band := case
        when v_pos.y < 33 then 'Front row'
        when v_pos.y < 66 then 'Middle row'
        else 'Back row'
    end;
    v_col_band := case
        when v_pos.x < 40 then 'left side'
        when v_pos.x > 60 then 'right side'
        else 'center'
    end;

    return jsonb_build_object(
        'status', 'ok',
        'dress_color', v_signup.dress_color,
        'movement_label', coalesce(v_movement.label, 'Movement ' || v_movement.movement_order),
        'position_text', v_row_band || ', ' || v_col_band
    );
end;
$$;

grant execute on function public.get_my_spot_by_phone(bigint, text, text) to anon;
