-- ============================================================================
-- MULTI-LOCATION SETUP — run once in the Supabase SQL editor.
--
-- The studio now operates two physical locations (Cremona, the existing one,
-- and a new one in Castelvetro Piacentino). This migration:
--   1. Creates a `locations` table and seeds both sites.
--   2. Tags every student/batch/expense with a location.
--   3. Turns `checkin_settings` from a hard singleton (CHECK id = 1) into one
--      row per location.
--   4. Updates the live self-check-in RPC to look up the student's own
--      location's settings instead of always reading id = 1.
--
-- Before running: confirm this matches your actual column names. The base
-- `students`/`attendance`/`expenses` tables were created directly in
-- Supabase, not tracked in this repo (only `alter table` migrations are) —
-- if the quick check below shows anything unexpected, stop and let me know
-- before the rest of this file runs.
--
--   select column_name from information_schema.columns
--   where table_schema = 'public' and table_name in ('students','expenses','batches','checkin_settings')
--   order by table_name, ordinal_position;
-- ============================================================================

-- ===== 1. Locations table =====
create table if not exists public.locations (
    id bigint generated by default as identity primary key,
    name text not null unique,
    address text not null,
    lat double precision not null,
    lng double precision not null,
    radius_meters int not null default 1000,
    active_days smallint[] not null,   -- JS Date.getDay(): 0=Sun..6=Sat
    start_time time not null,          -- check-in window open (includes the usual early buffer)
    end_time time not null,            -- check-in window close (includes the usual late buffer)
    created_at timestamptz not null default now()
);

-- Same trust model as batches/checkin_settings: both admin.html (authenticated)
-- and member.html (anon) need to read this directly.
alter table public.locations disable row level security;

insert into public.locations (name, address, lat, lng, radius_meters, active_days, start_time, end_time)
values
    ('Cremona', 'Corso XX Settembre 39, 26100 Cremona CR', 45.133938, 10.029063, 1000, '{6}', '13:15:00', '19:45:00'),
    ('Castelvetro Piacentino', '4X4R+G6, Castelvetro Piacentino, Province of Piacenza', 45.106313, 9.990563, 1000, '{0}', '15:45:00', '18:15:00')
on conflict (name) do nothing;

-- ===== 2. Tag students, batches, expenses with a location =====
-- Nullable first so the backfill below can run, then locked to NOT NULL —
-- every existing row belongs to Cremona (the only site that existed before
-- this migration).
alter table public.students add column if not exists location_id bigint references public.locations(id);
update public.students set location_id = (select id from public.locations where name = 'Cremona') where location_id is null;
alter table public.students alter column location_id set not null;

alter table public.batches add column if not exists location_id bigint references public.locations(id);
update public.batches set location_id = (select id from public.locations where name = 'Cremona') where location_id is null;
alter table public.batches alter column location_id set not null;

alter table public.expenses add column if not exists location_id bigint references public.locations(id);
update public.expenses set location_id = (select id from public.locations where name = 'Cremona') where location_id is null;
alter table public.expenses alter column location_id set not null;

-- ===== 3. checkin_settings: singleton -> one row per location =====
alter table public.checkin_settings drop constraint if exists checkin_settings_singleton;
alter table public.checkin_settings add column if not exists location_id bigint references public.locations(id);
update public.checkin_settings set location_id = (select id from public.locations where name = 'Cremona') where id = 1;
alter table public.checkin_settings alter column location_id set not null;
alter table public.checkin_settings add constraint checkin_settings_location_unique unique (location_id);

-- id was `smallint primary key default 1` — a fixed default, never a real
-- sequence, because this table was built to only ever hold one row. Now
-- that it holds one row per location, a plain insert (no explicit id) would
-- try to reuse id=1 and collide with the existing Cremona row. Converting to
-- a proper identity (starting after the existing row) fixes that for this
-- insert and every future location added the same way.
do $$
begin
    if not exists (
        select 1 from pg_attribute a
        join pg_class c on c.oid = a.attrelid
        where c.relname = 'checkin_settings' and a.attname = 'id' and a.attidentity <> ''
    ) then
        alter table public.checkin_settings alter column id drop default;
        alter table public.checkin_settings alter column id add generated by default as identity (start with 2);
    end if;
end $$;

insert into public.checkin_settings (location_id, active_days, start_time, end_time)
select id, active_days, start_time, end_time from public.locations where name = 'Castelvetro Piacentino'
on conflict (location_id) do nothing;

-- ===== 4. Self check-in RPC: look up the student's own location's window =====
-- Same body as v2_checkin_credit.sql's checkin_self_by_phone, with the
-- checkin_settings lookup changed from the old `where id = 1` to the
-- student's own location. No JS changes needed — member.html calls this
-- RPC the same way either way.
create or replace function public.checkin_self_by_phone(
    p_student_id bigint,
    p_phone text,
    p_passcode text default null
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_settings public.checkin_settings%rowtype;
    v_now_rome timestamp := (now() at time zone 'Europe/Rome');
    v_today    date      := (now() at time zone 'Europe/Rome')::date;
    v_existing public.attendance%rowtype;
    v_newly_present boolean := false;
    v_rate     numeric;
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return 'bad_phone';
    end if;

    if not public._passcode_matches_student(p_student_id, p_passcode) then
        return 'bad_passcode';
    end if;

    select cs.* into v_settings
    from public.checkin_settings cs
    join public.students s on s.location_id = cs.location_id
    where s.id = p_student_id;

    if not found
       or not (extract(dow from v_now_rome)::smallint = any (v_settings.active_days))
       or v_now_rome::time < v_settings.start_time
       or v_now_rome::time > v_settings.end_time then
        return 'closed';
    end if;

    select * into v_existing
    from public.attendance
    where studentid = p_student_id and attendancedate = v_today
    limit 1;

    if found then
        if v_existing.ispresent then
            return 'already';
        end if;
        update public.attendance
        set ispresent = true
        where id = v_existing.id;
        v_newly_present := true;
    else
        insert into public.attendance (studentid, attendancedate, ispresent, isdemo)
        values (p_student_id, v_today, true, false);
        v_newly_present := true;
    end if;

    if v_newly_present and v_today >= '2026-09-02'::date then
        select coalesce(per_class_rate, 10) into v_rate
        from public.students where id = p_student_id;

        update public.students
        set v2_credit_balance = coalesce(v2_credit_balance, 0) - v_rate
        where id = p_student_id;

        insert into public.v2_credit_transactions (student_id, type, amount, note, attendance_date)
        values (p_student_id, 'class_deduction', -v_rate, 'Class attendance — self check-in', v_today);
    end if;

    return 'checked_in';
end;
$$;

grant execute on function public.checkin_self_by_phone(bigint, text, text) to anon;

-- ===== Verify =====
select * from public.locations order by id;
select l.name, cs.* from public.checkin_settings cs join public.locations l on l.id = cs.location_id order by l.id;
select location_id, count(*) from public.students group by location_id;
select location_id, count(*) from public.batches group by location_id;
