-- ============================================================================
-- PERFORMANCE TIMELINE COMMENTS — run once in the Supabase SQL editor.
--
-- Powers the song-waveform timeline in admin.html's Choreography card:
-- clicking the wave lets the admin drop a movement OR a text comment at that
-- exact second in the song. Comments are admin-only for now (no member.html
-- surface yet) — same "authenticated_all" pattern as performance_signups/
-- performance_movements in performances.sql, since only admin.html touches
-- this table directly.
-- ============================================================================

create table if not exists public.performance_comments (
    id                bigint generated by default as identity primary key,
    performance_id    bigint not null references public.performances(id) on delete cascade,
    timestamp_seconds numeric not null,
    text              text not null,
    created_at        timestamptz not null default now()
);

alter table public.performance_comments enable row level security;

drop policy if exists "authenticated_all" on public.performance_comments;
create policy "authenticated_all" on public.performance_comments
    for all to authenticated using (true) with check (true);
