-- ============================================================================
-- PERFORMANCES — run once in the Supabase SQL editor
-- (Project -> SQL Editor -> New query -> paste -> Run).
--
-- Powers the new "Performances" tab in admin.html and the public
-- phone-verified perform.html page:
--   * performances            — one row per "performance call" the admin opens.
--   * performance_signups     — who joined, their roster tier/team/dress color.
--   * performance_movements   — ordered choreography steps, optionally tied to
--                                a time range in the uploaded song.
--   * performance_positions   — each dancer's x/y stage position per movement.
--   * performance_attendance  — rehearsal (not class) attendance per session.
--
-- Access model: TIGHTER than the older tables in this app. students/
-- attendance/fees_paid run with RLS off (accepted long ago, before phone
-- privacy mattered as much); this feature stores names next to dress colors
-- and stage positions, so RLS stays ON here:
--   * authenticated (logged-in admin)  — full read/write on every table.
--   * anon (public perform.html)       — SELECT on `performances` only
--     (to show the open call's title/date). Everything else — joining,
--     the joined-count, and "my spot" — goes through phone-verified
--     security-definer RPCs, which bypass RLS internally but never expose
--     other members' names/positions in their return values.
-- ============================================================================

-- ===== 1. Tables ============================================================
create table if not exists public.performances (
    id              bigint generated by default as identity primary key,
    title           text not null,
    event_date      date,
    status          text not null default 'open' check (status in ('open', 'closed')),
    front_band_pct  numeric not null default 25,
    song_url        text,
    created_at      timestamptz not null default now()
);

create table if not exists public.performance_signups (
    id              bigint generated by default as identity primary key,
    performance_id  bigint not null references public.performances(id) on delete cascade,
    student_id      bigint not null references public.students(id),
    student_name    text not null,
    roster_status   text not null default 'beginner'
                        check (roster_status in ('advanced', 'intermediate', 'beginner', 'spare')),
    team            text check (team in ('A', 'B')),  -- null = unassigned / spare pool
    dress_color     text check (dress_color in ('red', 'green', 'purple', 'orange', 'sky_blue', 'royal_blue')),
    joined_at       timestamptz not null default now(),
    unique (performance_id, student_id)
);

create table if not exists public.performance_movements (
    id              bigint generated by default as identity primary key,
    performance_id  bigint not null references public.performances(id) on delete cascade,
    movement_order  integer not null,
    label           text,
    start_seconds   numeric,
    end_seconds     numeric,
    unique (performance_id, movement_order)
);

create table if not exists public.performance_positions (
    id           bigint generated by default as identity primary key,
    movement_id  bigint not null references public.performance_movements(id) on delete cascade,
    student_id   bigint not null references public.students(id),
    x            numeric not null default 50,
    y            numeric not null default 50,
    unique (movement_id, student_id)
);

create table if not exists public.performance_attendance (
    id              bigint generated by default as identity primary key,
    performance_id  bigint not null references public.performances(id) on delete cascade,
    student_id      bigint not null references public.students(id),
    session_date    date not null,
    present         boolean not null default false,
    unique (performance_id, student_id, session_date)
);

-- ===== 2. Add gender to students (used to auto-balance teams/formations) ====
alter table public.students add column if not exists gender text check (gender in ('M', 'F'));
-- students.age already exists (the studentAge field in the admin add-student
-- form) — reused as-is for filtering, no schema change needed for it.

-- ===== 3. RLS: admin full access; anon gets only what perform.html needs ====
alter table public.performances enable row level security;
alter table public.performance_signups enable row level security;
alter table public.performance_movements enable row level security;
alter table public.performance_positions enable row level security;
alter table public.performance_attendance enable row level security;

drop policy if exists "authenticated_all" on public.performances;
create policy "authenticated_all" on public.performances
    for all to authenticated using (true) with check (true);

drop policy if exists "authenticated_all" on public.performance_signups;
create policy "authenticated_all" on public.performance_signups
    for all to authenticated using (true) with check (true);

drop policy if exists "authenticated_all" on public.performance_movements;
create policy "authenticated_all" on public.performance_movements
    for all to authenticated using (true) with check (true);

drop policy if exists "authenticated_all" on public.performance_positions;
create policy "authenticated_all" on public.performance_positions
    for all to authenticated using (true) with check (true);

drop policy if exists "authenticated_all" on public.performance_attendance;
create policy "authenticated_all" on public.performance_attendance
    for all to authenticated using (true) with check (true);

-- perform.html reads this directly (anon) just to show the open call's
-- title/date — nothing sensitive in this table.
drop policy if exists "anon_read_performances" on public.performances;
create policy "anon_read_performances" on public.performances
    for select to anon using (true);
-- No anon policy on performance_signups/performance_movements/
-- performance_positions/performance_attendance on purpose: those hold
-- names, dress colors, and stage positions, and are only ever reached by
-- anon through the security-definer RPCs below (which bypass RLS as the
-- function owner), never through a direct table read.

-- ===== 4. RPC: join a performance (phone-verified) ===========================
-- Same shape as request_manual_checkin_by_phone (phone_privacy.sql): re-checks
-- student id + phone together server-side, so a leaked/guessed id alone does
-- nothing. Derives the starting roster tier from the student's existing class
-- batch — 'spare' is never auto-assigned, only set manually by the admin.
create or replace function public.join_performance_by_phone(
    p_performance_id bigint,
    p_student_id bigint,
    p_phone text
)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_status text;
    v_name   text;
    v_batch  text;
    v_tier   text;
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return 'bad_phone';
    end if;

    select status into v_status from public.performances where id = p_performance_id;
    if v_status is null then
        return 'not_found';
    end if;
    if v_status <> 'open' then
        return 'closed';
    end if;

    select name, batch into v_name, v_batch from public.students where id = p_student_id;

    v_tier := case
        when v_batch in ('Advanced', 'Professional') then 'advanced'
        when v_batch = 'Intermediate' then 'intermediate'
        else 'beginner'
    end;

    insert into public.performance_signups (performance_id, student_id, student_name, roster_status)
    values (p_performance_id, p_student_id, v_name, v_tier)
    on conflict (performance_id, student_id) do nothing;

    return 'joined';
end;
$$;

grant execute on function public.join_performance_by_phone(bigint, bigint, text) to anon;

-- ===== 4b. RPC: how many dancers have joined (no names) ======================
-- performance_signups has no anon SELECT policy (it holds names), so
-- perform.html's "X dancers have joined so far" count goes through this
-- instead of a direct table read. No phone check needed — a count reveals
-- nothing about who joined.
create or replace function public.get_performance_signup_count(p_performance_id bigint)
returns integer
language sql
security definer
set search_path = public, pg_temp
as $$
    select count(*)::int from public.performance_signups where performance_id = p_performance_id;
$$;

grant execute on function public.get_performance_signup_count(bigint) to anon;

-- ===== 5. RPC: a dancer's own spot for the latest movement (phone-verified) =
-- Public pages never list every dancer's name/position (phone_privacy.sql's
-- whole point) — this returns only the caller's own dress color and a plain-
-- language position for the most recent movement of the performance they
-- most recently joined. Returns status: 'bad_phone' | 'not_joined' | 'no_movements' | 'ok'
create or replace function public.get_my_spot_by_phone(p_student_id bigint, p_phone text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_signup   public.performance_signups%rowtype;
    v_movement public.performance_movements%rowtype;
    v_pos      public.performance_positions%rowtype;
    v_row_band text;
    v_col_band text;
begin
    if not public._phone_matches_student(p_student_id, p_phone) then
        return jsonb_build_object('status', 'bad_phone');
    end if;

    select * into v_signup
    from public.performance_signups
    where student_id = p_student_id
    order by joined_at desc
    limit 1;

    if not found then
        return jsonb_build_object('status', 'not_joined');
    end if;

    select * into v_movement
    from public.performance_movements
    where performance_id = v_signup.performance_id
    order by movement_order desc
    limit 1;

    if not found then
        return jsonb_build_object('status', 'no_movements');
    end if;

    select * into v_pos
    from public.performance_positions
    where movement_id = v_movement.id and student_id = p_student_id;

    if not found then
        return jsonb_build_object('status', 'no_movements');
    end if;

    v_row_band := case
        when v_pos.y < 33 then 'Front row'
        when v_pos.y < 66 then 'Middle row'
        else 'Back row'
    end;
    v_col_band := case
        when v_pos.x < 40 then 'left side'
        when v_pos.x > 60 then 'right side'
        else 'center'
    end;

    return jsonb_build_object(
        'status', 'ok',
        'dress_color', v_signup.dress_color,
        'movement_label', coalesce(v_movement.label, 'Movement ' || v_movement.movement_order),
        'position_text', v_row_band || ', ' || v_col_band
    );
end;
$$;

grant execute on function public.get_my_spot_by_phone(bigint, text) to anon;

-- ===== 6. Public bucket for the rehearsal song ===============================
-- Same pattern as the 'site-gallery' bucket in site_content.sql: public
-- bucket (anyone with the URL can stream it), only the logged-in admin can
-- upload/replace it.
insert into storage.buckets (id, name, public)
values ('performance-songs', 'performance-songs', true)
on conflict (id) do update set public = true;

drop policy if exists "performance_songs_authenticated_all" on storage.objects;
create policy "performance_songs_authenticated_all" on storage.objects
    for all to authenticated
    using (bucket_id = 'performance-songs') with check (bucket_id = 'performance-songs');
