-- ============================================================================
-- FRIDAY PRACTICE SESSIONS — run once in the Supabase SQL editor
-- (Project -> SQL Editor -> New query -> paste -> Run).
--
-- One fixed practice list (students.in_practice_group), managed only from
-- admin.html's Attendance tab ("Friday practice" mode). Saving a practice
-- date charges every student on the list €5 — present OR absent — as a
-- v2_credit_transactions row of type 'practice_fee' (attendance_date = the
-- practice day). No new transaction table/column needed for that.
--
-- Practice attendance lives in its own table, NOT the shared attendance
-- table: that one is one row per student per day and drives the €10 class
-- charge, self check-in and active status — a student doing both a regular
-- class and practice on the same Friday would collide there, and the €10
-- refund logic (class_deduction + date) could reverse the wrong charge.
--
-- Admin-only: same RLS as v2_credit_transactions. Nothing here is exposed
-- to member.html / anon; members only see the resulting 'practice_fee' row
-- through the existing get_my_credit_ledger_v2_by_phone RPC.
-- ============================================================================

alter table public.students add column if not exists in_practice_group boolean not null default false;

create table if not exists public.practice_attendance (
    id bigint generated by default as identity primary key,
    student_id bigint not null,
    practice_date date not null,
    is_present boolean not null default false,
    created_at timestamptz not null default now(),
    unique (student_id, practice_date)
);

alter table public.practice_attendance enable row level security;

drop policy if exists "authenticated_all" on public.practice_attendance;
create policy "authenticated_all" on public.practice_attendance
    for all to authenticated using (true) with check (true);

revoke all on public.practice_attendance from anon;
