-- ============================================================================
-- WEBSITE CONTENT (gallery photos + events) — run once in the Supabase SQL
-- editor (Project -> SQL Editor -> New query -> paste -> Run).
--
-- Powers the "Website" tab in admin.html:
--   * site_gallery   — photos shown in the public homepage slideshow.
--                      Files live in the public 'site-gallery' storage bucket,
--                      this table stores their public URLs + display order.
--   * site_events    — kind='upcoming' (Upcoming Events section) and
--                      kind='past' (Recent Events section) on the homepage.
--   * site_instagram — reel/post links shown in the homepage's
--                      "Follow Us on Instagram" panel (6 slots).
--
-- Access model (same pattern as security_lockdown.sql):
--   * authenticated (logged-in admin) — full read/write.
--   * anon (public homepage)          — read-only SELECT, nothing else.
-- ============================================================================

-- ===== 1. Tables ============================================================
create table if not exists public.site_events (
    id         bigint generated by default as identity primary key,
    kind       text not null default 'upcoming' check (kind in ('upcoming', 'past')),
    event_date date not null,
    tba        boolean not null default false,   -- true = only the month is known
    title      text not null,
    venue      text not null default '',
    image_url  text,                              -- optional card background photo
    created_at timestamptz not null default now()
);

create table if not exists public.site_gallery (
    id           bigint generated by default as identity primary key,
    storage_path text not null,                   -- path inside the site-gallery bucket
    image_url    text not null,                   -- public URL served to visitors
    sort_order   integer not null default 0,      -- slideshow order, ascending
    created_at   timestamptz not null default now()
);

create table if not exists public.site_instagram (
    id         bigint generated by default as identity primary key,
    url        text not null,                     -- instagram.com/reel/... or /p/... link
    sort_order integer not null default 0,        -- panel order, ascending
    created_at timestamptz not null default now()
);

-- ===== 2. RLS: admin full access, public read-only ==========================
alter table public.site_events    enable row level security;
alter table public.site_gallery   enable row level security;
alter table public.site_instagram enable row level security;

drop policy if exists "authenticated_all" on public.site_events;
create policy "authenticated_all" on public.site_events
    for all to authenticated using (true) with check (true);

drop policy if exists "authenticated_all" on public.site_gallery;
create policy "authenticated_all" on public.site_gallery
    for all to authenticated using (true) with check (true);

drop policy if exists "anon_read_site_events" on public.site_events;
create policy "anon_read_site_events" on public.site_events
    for select to anon using (true);

drop policy if exists "anon_read_site_gallery" on public.site_gallery;
create policy "anon_read_site_gallery" on public.site_gallery
    for select to anon using (true);

drop policy if exists "authenticated_all" on public.site_instagram;
create policy "authenticated_all" on public.site_instagram
    for all to authenticated using (true) with check (true);

drop policy if exists "anon_read_site_instagram" on public.site_instagram;
create policy "anon_read_site_instagram" on public.site_instagram
    for select to anon using (true);

-- ===== 3. Storage: public 'site-gallery' bucket =============================
-- Public bucket: visitors load photos straight from the public object URL
-- (no policy needed for that). Only the logged-in admin can upload/delete.
insert into storage.buckets (id, name, public)
values ('site-gallery', 'site-gallery', true)
on conflict (id) do update set public = true;

drop policy if exists "site_gallery_authenticated_all" on storage.objects;
create policy "site_gallery_authenticated_all" on storage.objects
    for all to authenticated
    using (bucket_id = 'site-gallery') with check (bucket_id = 'site-gallery');

-- ===== 4. Seed: the two events currently hardcoded in index.html ============
-- (Only inserted if the table is empty, so re-running this file is safe.)
insert into public.site_events (kind, event_date, tba, title, venue, image_url)
select * from (values
    ('upcoming', date '2026-07-25', false, 'Performance by our students',    'Castelvetro · 7:00 PM',            'gallery/photo-14.jpg'),
    ('upcoming', date '2026-10-01', true,  'In-Studio Bhangra Competition',  'Bhangra Sway Studio, Cremona',     'gallery/photo-01.jpg')
) as seed(kind, event_date, tba, title, venue, image_url)
where not exists (select 1 from public.site_events);

-- Seed: the 6 reels currently hardcoded in index.html's Instagram panel.
insert into public.site_instagram (url, sort_order)
select * from (values
    ('https://www.instagram.com/reel/DaZ4fXdMW8J/', 1),
    ('https://www.instagram.com/reel/DX3y2NEM2q4/', 2),
    ('https://www.instagram.com/reel/DWXDTvPDLb9/', 3),
    ('https://www.instagram.com/reel/DULjUSXjIwX/', 4),
    ('https://www.instagram.com/reel/DTvJRBPjF9u/', 5),
    ('https://www.instagram.com/reel/DZ1vQOfsM4-/', 6)
) as seed(url, sort_order)
where not exists (select 1 from public.site_instagram);
