-- ============================================================================
-- V2 CUTOVER — run once in the Supabase SQL editor
-- (Project -> SQL Editor -> New query -> paste -> Run).
--
-- Supports admin_v2.html / member_v2.html — the fresh, single-billing-model
-- rebuild (credit balance only, no legacy monthly-cycle engine). Every other
-- table (students, attendance, batches, tax_records, credit_transactions,
-- performances, etc.) is reused exactly as-is; this is the only schema
-- change the new pages need.
--
-- pre_cutover_balance_snapshot is filled in BY HAND per student in
-- admin_v2.html (checked against the existing admin.html's reports), never
-- computed automatically and never read by any live balance/deduction
-- logic — it's a permanent, disconnected reference number only.
--
-- The LIVE balance is a completely separate column/table from the old
-- system's credit_balance / credit_transactions (which admin.html keeps
-- using unmodified). Reusing those would immediately break the "fresh
-- start at €0" idea — they already carry a full session's worth of real
-- and test activity. v2_credit_balance starts at 0 for every student and
-- only ever moves through v2_credit_transactions rows written by
-- admin_v2.html. Old admin.html/member.html never read or write either.
-- ============================================================================

alter table public.students add column if not exists pre_cutover_balance_snapshot numeric;
alter table public.students add column if not exists pre_cutover_balance_updated_at timestamptz;

alter table public.students add column if not exists v2_credit_balance numeric not null default 0;

-- Same append-only-ledger shape as the old credit_transactions, plus a real
-- attendance_date column (the old table encoded the date into a note string
-- as a workaround — cleaner to just have the column from the start) so a
-- class_deduction row can always be found again unambiguously when that
-- date's attendance is unmarked.
create table if not exists public.v2_credit_transactions (
    id bigint generated by default as identity primary key,
    student_id bigint not null,
    type text not null, -- 'recharge' | 'class_deduction' | 'adjustment'
    amount numeric not null,
    note text,
    attendance_date date,
    created_at timestamptz not null default now()
);

alter table public.v2_credit_transactions enable row level security;

drop policy if exists "authenticated_all" on public.v2_credit_transactions;
create policy "authenticated_all" on public.v2_credit_transactions
    for all to authenticated using (true) with check (true);

revoke all on public.v2_credit_transactions from anon;
